### ISSUE TITLE
Date goes off the right side of the screen

### ISSUE THREAD

**Issue by Izaic** [JF002/InfiniTime#116]
The date WEDNESDAY 28 OCT 2020 goes of the screen on the right side with the 2020 clipped so that only 202 shows.

**Comment by thelovebug** [comment]
Might I suggest that if the month is being abbreviated, then the day should be also.

Having said that, today: "SATURDAY 31 OCT 2020" fits perfectly and looks amazing.

**Comment by JF002** [comment]
Mhm when I implemented this, the whole date was displayed... It was in 2019, I guess!

**Comment by x2k13** [comment]
Suggestion:
I don't know if this is possible, since I have no idea how to code that, but how about setting a slightly smaller font size and use  center alignment instead of left alignment. This would make sure the date is always in the middle and not cut off to either of the sides. What do you think?

**Comment by JF002** [comment]
Fixed in 0.15
