### ISSUE TITLE
Timer functionality. 

### ISSUE THREAD

**Issue by Raupinger** [JF002/InfiniTime#344]
Add a timer, that can be set, triggering a vibration when it runs out. A good way to put this in the UI might be with a left/right swipe on the stopwatch app.

**Comment by pfeerick** [comment]
I was sure this had been mentioned in another issue, but perhaps it was only on the chat platform. 

Anyway, I would prefer this gets its own icon, rather than embedded in another app... It makes a little more sense on a phone as you have the screen realestate to have nice big buttons and link it all under a clock app, but I think single task apps suit a watch better.

**Comment by JF002** [comment]
That's actually a feature I would like to see in InfiniTime in the near future :)
I agree with @pfeerick , I think this functionality deserves its own app.

**Comment by Raupinger** [comment]
PR is merged, I'll close this
