### ISSUE TITLE
Metronome arc is laggy 

### ISSUE THREAD

**Issue by Itai-Nelken** [JF002/InfiniTime#491]
On latest commit.

https://user-images.githubusercontent.com/70802936/125686791-d97e00e6-2d97-4c81-8f7a-e96605eeab57.mp4

**Comment by Itai-Nelken** [comment]
Also as you see in the video, it jumped to 900 bpm, but that's a different issue.

**Comment by Riksu9000** [comment]
This started happening after LVGL was set to use the system timer as it's tick source. This is odd as the change doesn't seem like it should relate to this behaviour. There are more things that have slightly changed.

Buttons now seem to be aware of when they're released, which is odd as I thought LVGL would detect all touches as short taps because of this line. In stopwatch for example, the buttons are set to activate on `LV_EVENT_PRESSED`, which is the act of pressing, but not releasing.

https://github.com/JF002/InfiniTime/blob/57b339707861c5688f5d432f1506a99df6bb0fce/src/displayapp/LittleVgl.cpp#L180

Then I think this lag in metronome is due to LVGL thinking the screen is being tapped repeatedly. It would also explain why the bpm jumps to 900 when we touch the middle, and why the dropdown closes immediatly on tapping an option.

**Comment by JF002** [comment]
As @Riksu9000 wrote, this behavior appeared when we merged https://github.com/JF002/InfiniTime/pull/488.
